import request from '@/utils/request'
export const listStaff = params => request({ url: '/live/gift/staff', method: 'get', params })
export const listGiftShopOptions = () => request({ url: '/live/gift/shop-options', method: 'get' })
export const listShops = params => request({ url: '/live/gift/shop', method: 'get', params })
export const getShop = id => request({ url: `/live/gift/shop/${id}`, method: 'get' })
export const saveShop = data => request({ url: '/live/gift/shop', method: 'post', data })
export const listRooms = params => request({ url: '/live/gift/room', method: 'get', params })
export const getRoom = id => request({ url: `/live/gift/room/${id}`, method: 'get' })
export const saveRoom = data => request({ url: '/live/gift/room', method: 'post', data })
export const listMappings = params => request({ url: '/live/gift/mapping', method: 'get', params })
export const saveMapping = data => request({ url: '/live/gift/mapping', method: 'post', data })
export const listTemplates = () => request({ url: '/live/gift/template', method: 'get' })
export const getTemplate = id => request({ url: `/live/gift/template/${id}`, method: 'get' })
export const saveTemplate = data => request({ url: '/live/gift/template', method: 'post', data })
export const deleteTemplate = id => request({ url: `/live/gift/template/${id}`, method: 'delete' })
export const listDaily = params => request({ url: '/live/gift/daily', method: 'get', params })
export const getDaily = id => request({ url: `/live/gift/daily/${id}`, method: 'get' })
export const saveDaily = data => request({ url: '/live/gift/daily', method: 'post', data })
export const listGifts = params => request({ url: '/live/gift/catalog', method: 'get', params })
export const getGift = id => request({ url: `/live/gift/catalog/${id}`, method: 'get' })
export const saveGift = data => request({ url: '/live/gift/catalog', method: 'post', data })
export const saveGiftPreference = data => request({ url: '/live/gift/catalog/preference', method: 'post', data })
export const addGiftCost = data => request({ url: '/live/gift/catalog/cost', method: 'post', data })
export const importGiftCosts = data => request({ url: '/live/gift/catalog/import', method: 'post', data, headers: { 'Content-Type': 'multipart/form-data' } })
export const getGiftOrder = no => request({ url: `/live/gift/order/${encodeURIComponent(no)}`, method: 'get' })
export const saveOrderGifts = data => request({ url: '/live/gift/order', method: 'post', data })
export const getRoomPreference = () => request({ url: '/live/gift/room-preference', method: 'get' })
export const saveRoomPreference = data => request({ url: '/live/gift/room-preference', method: 'post', data })
export const batchSaveOrderGifts = data => request({ url: '/live/gift/order/batch', method: 'post', data })
export const listGiftLedger = params => request({ url: '/live/gift/ledger', method: 'get', params })
export const getGiftSummary = params => request({ url: '/live/gift/summary', method: 'get', params })
export const listGiftInventory = params => request({ url: '/live/gift/inventory', method: 'get', params })
export const getGiftInventorySummary = params => request({ url: '/live/gift/inventory/summary', method: 'get', params })
export const listGiftInventoryMovements = params => request({ url: '/live/gift/inventory/movements', method: 'get', params })
export const adjustGiftInventory = data => request({ url: '/live/gift/inventory/adjust', method: 'post', data })
