<template>
  <div class="app-container gift-entry">
    <div class="page-head">
      <div><h2>订单录礼品</h2><p>输入订单号后选择标准礼品，系统自动计算成本。</p></div>
      <div class="head-actions"><el-select v-model="form.dailyId" clearable placeholder="选择当天直播登记" style="width:320px"><el-option v-for="item in daily" :key="item.dailyId" :value="item.dailyId" :label="`${item.liveDate} · ${item.shopName} / ${item.roomName}`"/></el-select><el-button icon="Files" @click="batchVisible=true">批量录入</el-button></div>
    </div>
    <div class="order-search"><el-input ref="orderInput" v-model.trim="orderNo" size="large" clearable placeholder="粘贴或扫描订单号，按回车查找" @keyup.enter="findOrder"><template #prepend>订单号</template></el-input><el-button type="primary" size="large" :loading="loading" @click="findOrder">查找</el-button></div>
    <el-empty v-if="!order" description="输入订单号后开始录入"/>
    <template v-else>
      <div class="order-band"><div><span>订单号</span><strong>{{order.orderNo}}</strong></div><div><span>商品</span><strong>{{order.productName||'-'}}</strong></div><div><span>店铺</span><strong>{{order.shopName||'-'}}</strong></div><div><span>订单日期</span><strong>{{order.orderDate}}</strong></div><div><span>成交金额</span><strong>¥{{money(order.payAmount)}}</strong></div></div>
      <div class="status-row"><span>本单礼品情况</span><el-radio-group v-model="form.processStatus"><el-radio-button value="selected">已选择礼品</el-radio-button><el-radio-button value="customer_declined">顾客未选择</el-radio-button><el-radio-button value="not_applicable">本单不送礼品</el-radio-button><el-radio-button value="pending">稍后确认</el-radio-button></el-radio-group></div>
      <gift-picker v-if="form.processStatus==='selected'" v-model="form.gifts" :catalog="gifts" v-model:keyword="keyword" @search="searchGifts"/>
      <el-input v-model="form.operatorNote" type="textarea" :rows="2" maxlength="500" show-word-limit placeholder="补充说明（可选，不参与成本计算）"/>
      <div class="actions"><el-button @click="clearOrder">取消</el-button><el-button type="primary" :loading="saving" @click="submit(false)">保存</el-button><el-button type="primary" plain :loading="saving" @click="submit(true)">保存并录下一单</el-button></div>
    </template>

    <el-dialog v-model="batchVisible" title="批量订单录礼品" width="920px" destroy-on-close>
      <div class="batch-layout"><div><div class="field-title">订单号</div><el-input v-model="batch.orderText" type="textarea" :rows="15" placeholder="每行一个订单号，最多500个"/><div class="field-help">已识别 {{batchOrderNos.length}} 个不重复订单</div></div><div><div class="field-title">选择礼品</div><gift-picker v-model="batch.gifts" compact :catalog="gifts" v-model:keyword="keyword" @search="searchGifts"/></div></div>
      <el-input v-model="batch.operatorNote" class="batch-note" placeholder="批量录入说明（可选）"/>
      <div v-if="batchResult" class="batch-result"><strong>处理完成：成功 {{batchResult.success}}，失败 {{batchResult.failure}}</strong><el-scrollbar v-if="batchResult.failures?.length" max-height="150px"><div v-for="item in batchResult.failures" :key="item" class="failure">{{item}}</div></el-scrollbar></div>
      <template #footer><el-button @click="batchVisible=false">关闭</el-button><el-button type="primary" :loading="batchSaving" @click="submitBatch">确认批量录入</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup name="GiftEntry">
import { batchSaveOrderGifts,getGiftOrder,listDaily,listGifts,saveOrderGifts } from '@/api/live/gift'
const { proxy }=getCurrentInstance();const orderInput=ref(),orderNo=ref(''),order=ref(),daily=ref([]),gifts=ref([]),keyword=ref('');const loading=ref(false),saving=ref(false),batchVisible=ref(false),batchSaving=ref(false),batchResult=ref();const form=ref({processStatus:'selected',dailyId:null,gifts:[],operatorNote:''});const batch=ref({orderText:'',gifts:[],operatorNote:''});let timer
const batchOrderNos=computed(()=>[...new Set(batch.value.orderText.split(/\r?\n|,|，/).map(x=>x.trim()).filter(Boolean))])
function money(value){return Number(value||0).toFixed(2)}
async function findOrder(){if(!orderNo.value)return proxy.$modal.msgWarning('请输入订单号');loading.value=true;try{const response=await getGiftOrder(orderNo.value);order.value=response.data;await searchGifts();form.value.processStatus=response.data.giftStatus?.processStatus||'selected';form.value.dailyId=response.data.giftStatus?.dailyId||form.value.dailyId;form.value.operatorNote=response.data.giftStatus?.operatorNote||'';form.value.gifts=(response.data.gifts||[]).map(item=>({...item,currentCost:item.unitCost}))}finally{loading.value=false}}
function searchGifts(){clearTimeout(timer);return new Promise(resolve=>{timer=setTimeout(async()=>{gifts.value=(await listGifts({keyword:keyword.value,status:'0',costDate:order.value?.orderDate})).data||[];resolve()},180)})}
async function submit(next){saving.value=true;try{await saveOrderGifts({orderNo:order.value.orderNo,...form.value,gifts:form.value.processStatus==='selected'?form.value.gifts.map(x=>({giftId:x.giftId,quantity:x.quantity})):[]});proxy.$modal.msgSuccess('礼品记录已保存');if(next)clearOrder()}finally{saving.value=false}}
async function submitBatch(){if(!batchOrderNos.value.length)return proxy.$modal.msgWarning('请输入订单号');if(!batch.value.gifts.length)return proxy.$modal.msgWarning('请选择礼品');batchSaving.value=true;try{const response=await batchSaveOrderGifts({orderNos:batchOrderNos.value,dailyId:form.value.dailyId,gifts:batch.value.gifts.map(x=>({giftId:x.giftId,quantity:x.quantity})),operatorNote:batch.value.operatorNote});batchResult.value=response.data;proxy.$modal.msgSuccess(`批量处理完成，成功 ${response.data.success} 个订单`)}finally{batchSaving.value=false}}
function clearOrder(){order.value=null;orderNo.value='';form.value={processStatus:'selected',dailyId:form.value.dailyId,gifts:[],operatorNote:''};nextTick(()=>orderInput.value?.focus())}
onMounted(async()=>{const today=new Date().toISOString().slice(0,10);daily.value=(await listDaily({beginDate:today,endDate:today})).data||[];searchGifts();nextTick(()=>orderInput.value?.focus())})
</script>

<script>
const GiftPicker={props:{modelValue:{type:Array,default:()=>[]},catalog:{type:Array,default:()=>[]},keyword:String,compact:Boolean},emits:['update:modelValue','update:keyword','search'],setup(props,{emit}){const selected=computed(()=>props.modelValue);const choose=item=>{if(item.currentCost==null)return;const rows=props.modelValue.map(x=>({...x}));const old=rows.find(x=>x.giftId===item.giftId);old?old.quantity=Math.min(10,old.quantity+1):rows.push({...item,quantity:1});emit('update:modelValue',rows)};const remove=item=>emit('update:modelValue',props.modelValue.filter(x=>x.giftId!==item.giftId));const updateQuantity=(item,value)=>emit('update:modelValue',props.modelValue.map(x=>x.giftId===item.giftId?{...x,quantity:Math.min(10,Math.max(1,Number(value)||1))}:x));const total=computed(()=>selected.value.reduce((sum,x)=>sum+Number(x.currentCost||0)*Number(x.quantity||0),0));return{selected,choose,remove,updateQuantity,total,money:v=>Number(v||0).toFixed(2)}} ,template:`<div class="picker" :class="{compact}"><div class="gift-pick"><el-input :model-value="keyword" clearable placeholder="搜索名称、编码、简称或别名" @update:model-value="$emit('update:keyword',$event)" @input="$emit('search')"/><div class="gift-grid"><button v-for="item in catalog" :key="item.giftId" type="button" @click="choose(item)"><strong>{{item.giftName}}</strong><span>{{item.specification||item.unit}} · ¥{{money(item.currentCost)}}</span></button></div></div><div class="selected"><el-empty v-if="!selected.length" description="还没有选择礼品" :image-size="60"/><div v-for="item in selected" :key="item.giftId" class="selected-row"><div><strong>{{item.giftName}}</strong><span>{{item.specification||item.unit}}</span></div><el-input-number :model-value="item.quantity" :min="1" :max="10" @change="updateQuantity(item,$event)"/><b>¥{{money(Number(item.currentCost||0)*item.quantity)}}</b><el-button link type="danger" icon="Delete" @click="remove(item)"/></div><div class="total"><span>共 {{selected.reduce((s,x)=>s+Number(x.quantity||0),0)}} 件</span><strong>成本 ¥{{money(total)}}</strong></div></div></div>`}
export default{components:{GiftPicker}}
</script>

<style scoped>.gift-entry{max-width:1500px}.page-head,.head-actions,.order-search,.status-row,.actions,.total{display:flex;align-items:center;justify-content:space-between;gap:12px}.page-head h2{margin:0 0 4px;font-size:22px}.page-head p{margin:0;color:#6b7280}.order-search{margin:18px 0}.order-band{display:grid;grid-template-columns:1.1fr 2fr 1fr 1fr 1fr;padding:14px;border:1px solid #e5e7eb;background:#f8fafc}.order-band div{display:flex;flex-direction:column;gap:4px}.order-band span{color:#909399;font-size:12px}.status-row{justify-content:flex-start;padding:16px 0}.status-row>span{font-weight:600}.actions{justify-content:flex-end;margin-top:14px}.batch-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:16px}.field-title{margin-bottom:8px;font-weight:600}.field-help{margin-top:5px;color:#909399;font-size:12px}.batch-note{margin-top:14px}.batch-result{margin-top:14px;padding:12px;background:#f0fdf4}.failure{padding:3px 0;color:#dc2626;font-size:12px}@media(max-width:900px){.order-band{grid-template-columns:1fr 1fr}.batch-layout{grid-template-columns:1fr}.page-head{align-items:flex-start}.head-actions{flex-direction:column;align-items:flex-end}}</style>

<style>.gift-entry .picker{display:grid;grid-template-columns:1fr 1.15fr;gap:18px;margin-bottom:18px}.gift-entry .gift-pick,.gift-entry .selected{border:1px solid #e5e7eb;padding:14px}.gift-entry .gift-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:12px;max-height:350px;overflow:auto}.gift-entry .gift-grid button{display:flex;flex-direction:column;gap:5px;padding:10px;border:1px solid #dfe3e8;border-radius:4px;background:#fff;text-align:left;cursor:pointer}.gift-entry .gift-grid button:hover{border-color:#f97316;background:#fff7ed}.gift-entry .gift-grid span,.gift-entry .selected-row span{color:#6b7280;font-size:12px}.gift-entry .selected-row{display:grid;grid-template-columns:minmax(0,1fr) 130px 90px 32px;align-items:center;gap:8px;padding:10px 0;border-bottom:1px solid #eee}.gift-entry .selected-row>div{display:flex;flex-direction:column}.gift-entry .selected-row b{text-align:right}.gift-entry .total{padding:14px 0}.gift-entry .total strong{color:#ea580c;font-size:20px}.gift-entry .picker.compact{grid-template-columns:1fr}.gift-entry .picker.compact .gift-grid{grid-template-columns:repeat(2,minmax(0,1fr));max-height:190px}@media(max-width:900px){.gift-entry .picker{grid-template-columns:1fr}.gift-entry .gift-grid{grid-template-columns:1fr 1fr}}</style>
