package com.xinke.erp.mapper;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FinanceCoreMapper
{
    List<Map<String, Object>> selectPeriodList(Map<String, Object> query);
    List<Map<String, Object>> selectSubjectList(Map<String, Object> query);
    List<Map<String, Object>> selectFeeTypeList(Map<String, Object> query);
    List<Map<String, Object>> selectPlatformAccountList(Map<String, Object> query);
    List<Map<String, Object>> selectBankAccountList(Map<String, Object> query);
    List<Map<String, Object>> selectSettlementList(Map<String, Object> query);
    List<Map<String, Object>> selectReceivableList(Map<String, Object> query);
    List<Map<String, Object>> selectPayableList(Map<String, Object> query);
    List<Map<String, Object>> selectCashFlowList(Map<String, Object> query);
    Map<String, Object> selectCashFlowSummary(Map<String, Object> query);
    List<Map<String, Object>> selectCashFlowAccountOptions();
    List<Map<String, Object>> selectExpenseList(Map<String, Object> query);
    List<Map<String, Object>> selectVoucherList(Map<String, Object> query);
    List<Map<String, Object>> selectReconcileTaskList(Map<String, Object> query);
    List<Map<String, Object>> selectReconcileDiffList(Map<String, Object> query);
    Map<String, Object> selectReconcileDiffByNo(@Param("diffNo") String diffNo);
    List<Map<String, Object>> selectPeriodCloseList(Map<String, Object> query);
    Map<String, Object> selectFinanceDashboardSummary();
    List<Map<String, Object>> selectFinanceCashTrend();
    List<Map<String, Object>> selectFinanceRecentActivities();
    List<Map<String, Object>> selectLedgerList(Map<String, Object> query);
    List<Map<String, Object>> selectTrialBalanceList(Map<String, Object> query);
    Map<String, Object> selectTrialBalanceSummary(Map<String, Object> query);
    Map<String, Object> selectPayableSummary(Map<String, Object> query);
    List<Map<String, Object>> selectPayableAging(Map<String, Object> query);
    List<Map<String, Object>> selectSupplierInvoiceList(Map<String, Object> query);
    List<Map<String, Object>> selectSupplierInvoiceItemList(@Param("invoiceNo") String invoiceNo);
    List<Map<String, Object>> selectInvoicePurchaseOptions(Map<String, Object> query);
    Map<String, Object> selectInvoicePurchaseByNo(@Param("purchaseNo") String purchaseNo);
    List<Map<String, Object>> selectInvoicePurchaseItemList(@Param("purchaseNo") String purchaseNo);
    List<Map<String, Object>> selectPaymentRequestList(Map<String, Object> query);
    List<Map<String, Object>> selectBankAccountOptions();

    Map<String, Object> selectSettlementByNo(@Param("settlementNo") String settlementNo);
    Map<String, Object> selectReceivableByNo(@Param("receivableNo") String receivableNo);
    Map<String, Object> selectPayableByNo(@Param("payableNo") String payableNo);
    Map<String, Object> selectSupplierInvoiceByNo(@Param("invoiceNo") String invoiceNo);
    Map<String, Object> selectSupplierInvoiceBySupplierNo(@Param("supplierId") Long supplierId,
        @Param("supplierInvoiceNo") String supplierInvoiceNo);
    Map<String, Object> selectPaymentRequestByNo(@Param("paymentNo") String paymentNo);
    Map<String, Object> selectBankAccountById(@Param("bankAccountId") Long bankAccountId);
    BigDecimal selectReservedPaymentAmount(@Param("payableNo") String payableNo);
    Map<String, Object> selectCashFlowByNo(@Param("flowNo") String flowNo);
    Map<String, Object> selectExpenseByNo(@Param("expenseNo") String expenseNo);
    Map<String, Object> selectFeeTypeByCode(@Param("feeCode") String feeCode);
    Map<String, Object> selectVoucherByNo(@Param("voucherNo") String voucherNo);
    Map<String, Object> selectVoucherBySource(@Param("sourceType") String sourceType, @Param("sourceNo") String sourceNo);
    List<Map<String, Object>> selectVoucherEntryList(@Param("voucherNo") String voucherNo);
    List<Map<String, Object>> selectSettlementReconcileRows(Map<String, Object> query);
    Map<String, Object> selectCloseCheckSummary(@Param("periodCode") String periodCode);
    Map<String, Object> selectPeriodCloseByCode(@Param("periodCode") String periodCode, @Param("closeScope") String closeScope);

    int insertSettlement(Map<String, Object> form);
    int updateSettlementDraft(Map<String, Object> form);
    int voidSettlementDraft(Map<String, Object> form);
    int updateSettlementApproved(Map<String, Object> form);
    int updateSettlementReconcileResult(Map<String, Object> form);
    int insertReceivable(Map<String, Object> form);
    int updateReceivableWriteoff(Map<String, Object> form);
    int insertCashFlow(Map<String, Object> form);
    int voidCashFlowDraft(Map<String, Object> form);
    int updateCashFlowPosted(Map<String, Object> form);
    int updateCashFlowVoucher(Map<String, Object> form);
    int updateCashFlowReversed(Map<String, Object> form);
    int updateCashFlowMatched(Map<String, Object> form);
    int insertWriteoffRecord(Map<String, Object> form);
    int insertExpense(Map<String, Object> form);
    int updateExpenseDraft(Map<String, Object> form);
    int voidExpenseDraft(Map<String, Object> form);
    int updateExpenseApproved(Map<String, Object> form);
    int insertPayable(Map<String, Object> form);
    int updatePayableWriteoff(Map<String, Object> form);
    int insertSupplierInvoice(Map<String, Object> form);
    int insertSupplierInvoiceItem(Map<String, Object> form);
    int updateSupplierInvoiceApproved(Map<String, Object> form);
    int insertPaymentRequest(Map<String, Object> form);
    int updatePaymentRequestApproved(Map<String, Object> form);
    int updatePaymentRequestRejected(Map<String, Object> form);
    int updatePaymentRequestPaid(Map<String, Object> form);
    int insertPaymentExecute(Map<String, Object> form);
    int insertVoucher(Map<String, Object> form);
    int insertVoucherEntry(Map<String, Object> form);
    int updateVoucherPosted(Map<String, Object> form);
    int selectLedgerEntryCount(@Param("voucherNo") String voucherNo);
    int insertLedgerEntriesFromVoucher(@Param("voucherNo") String voucherNo);
    int deleteTrialBalanceByPeriod(@Param("periodCode") String periodCode);
    int rebuildTrialBalance(@Param("periodCode") String periodCode);
    int insertReconcileTask(Map<String, Object> form);
    int insertReconcileDiff(Map<String, Object> form);
    int updateReconcileTaskResult(Map<String, Object> form);
    int updateReconcileDiffResolved(Map<String, Object> form);
    int insertPeriodClose(Map<String, Object> form);
    int updatePeriodCloseCheck(Map<String, Object> form);
    int updatePeriodClosed(Map<String, Object> form);
    int updatePeriodReopened(Map<String, Object> form);
    int updateAccountPeriodClosed(Map<String, Object> form);
    int updateAccountPeriodReopened(Map<String, Object> form);
}
