-- Douyin live viewer lead tracking schema
-- A viewer is reported at most once per day by the extension.
-- Comments are attached to the daily viewer lead by sec_uid when available, otherwise by same-day nickname.

CREATE TABLE IF NOT EXISTS dy_viewer (
  viewer_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Viewer ID',
  sec_uid VARCHAR(128) NOT NULL COMMENT 'Douyin sec_uid',
  nickname VARCHAR(100) DEFAULT NULL COMMENT 'Nickname',
  avatar VARCHAR(1000) DEFAULT NULL COMMENT 'Avatar URL',
  gender TINYINT DEFAULT 0 COMMENT 'Gender from Douyin',
  first_seen_date DATE DEFAULT NULL COMMENT 'First seen date',
  last_seen_date DATE DEFAULT NULL COMMENT 'Last seen date',
  has_comment TINYINT DEFAULT 0 COMMENT 'Has comments',
  comment_count INT DEFAULT 0 COMMENT 'Comment count',
  first_comment_time DATETIME DEFAULT NULL COMMENT 'First comment time',
  last_comment_time DATETIME DEFAULT NULL COMMENT 'Last comment time',
  last_comment_content VARCHAR(1000) DEFAULT NULL COMMENT 'Last comment content',
  status VARCHAR(32) DEFAULT 'new' COMMENT 'new/following/ordered/invalid',
  intent VARCHAR(32) DEFAULT 'unknown' COMMENT 'unknown/low/medium/high',
  owner_id BIGINT DEFAULT NULL COMMENT 'Owner user ID',
  owner_name VARCHAR(50) DEFAULT NULL COMMENT 'Owner name',
  owner_assigned_time DATETIME DEFAULT NULL COMMENT 'Owner assigned time',
  order_no VARCHAR(64) DEFAULT NULL COMMENT 'Matched order number',
  remark VARCHAR(500) DEFAULT NULL COMMENT 'Remark',
  last_follow_time DATETIME DEFAULT NULL COMMENT 'Last follow time',
  manual_update_time DATETIME DEFAULT NULL COMMENT 'Manual update time',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (viewer_id),
  UNIQUE KEY uk_sec_uid (sec_uid),
  KEY idx_nickname (nickname),
  KEY idx_owner_status (owner_id, status),
  KEY idx_status_seen (status, last_seen_date),
  KEY idx_has_comment (has_comment),
  KEY idx_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Douyin viewer profile';

CREATE TABLE IF NOT EXISTS dy_viewer_daily_lead (
  lead_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Lead ID',
  lead_date DATE NOT NULL COMMENT 'Viewer date',
  room_key VARCHAR(64) NOT NULL COMMENT 'Capture room key',
  douyin_user_id VARCHAR(64) DEFAULT NULL COMMENT 'Douyin user ID',
  live_room_name VARCHAR(100) DEFAULT NULL COMMENT 'Live room name',
  viewer_id BIGINT NOT NULL COMMENT 'Viewer ID',
  sec_uid VARCHAR(128) NOT NULL COMMENT 'Douyin sec_uid',
  nickname VARCHAR(100) DEFAULT NULL COMMENT 'Nickname',
  avatar VARCHAR(1000) DEFAULT NULL COMMENT 'Avatar URL',
  has_comment TINYINT DEFAULT 0 COMMENT 'Has comments',
  comment_count INT DEFAULT 0 COMMENT 'Comment count',
  first_comment_time DATETIME DEFAULT NULL COMMENT 'First comment time',
  last_comment_time DATETIME DEFAULT NULL COMMENT 'Last comment time',
  last_comment_content VARCHAR(1000) DEFAULT NULL COMMENT 'Last comment content',
  status VARCHAR(32) DEFAULT 'new' COMMENT 'new/following/ordered/lost/invalid',
  intent VARCHAR(32) DEFAULT 'unknown' COMMENT 'unknown/interested/strong',
  owner_id BIGINT DEFAULT NULL COMMENT 'Owner user ID',
  owner_name VARCHAR(50) DEFAULT NULL COMMENT 'Owner name',
  order_no VARCHAR(64) DEFAULT NULL COMMENT 'Matched order number',
  remark VARCHAR(500) DEFAULT NULL COMMENT 'Remark',
  last_follow_time DATETIME DEFAULT NULL COMMENT 'Last follow time',
  next_follow_time DATETIME DEFAULT NULL COMMENT 'Next follow time',
  manual_update_time DATETIME DEFAULT NULL COMMENT 'Manual update time',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (lead_id),
  UNIQUE KEY uk_day_room_viewer (lead_date, room_key, sec_uid),
  KEY idx_date_status (lead_date, status),
  KEY idx_owner_status (owner_id, status),
  KEY idx_has_comment (has_comment),
  KEY idx_order_no (order_no),
  KEY idx_viewer (viewer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Douyin daily viewer lead';

CREATE TABLE IF NOT EXISTS dy_viewer_comment (
  comment_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Comment ID',
  lead_id BIGINT DEFAULT NULL COMMENT 'Lead ID',
  viewer_id BIGINT DEFAULT NULL COMMENT 'Viewer ID',
  lead_date DATE NOT NULL COMMENT 'Comment date',
  room_key VARCHAR(64) NOT NULL COMMENT 'Capture room key',
  douyin_user_id VARCHAR(64) DEFAULT NULL COMMENT 'Douyin user ID',
  sec_uid VARCHAR(128) DEFAULT NULL COMMENT 'Douyin sec_uid',
  nickname VARCHAR(100) DEFAULT NULL COMMENT 'Nickname',
  content VARCHAR(1000) NOT NULL COMMENT 'Comment content',
  dedupe_key VARCHAR(255) NOT NULL COMMENT 'Dedupe key',
  match_type VARCHAR(32) DEFAULT 'nickname' COMMENT 'sec_uid/nickname/unmatched',
  source VARCHAR(64) DEFAULT NULL COMMENT 'Source',
  page_url VARCHAR(1000) DEFAULT NULL COMMENT 'Page URL',
  captured_at DATETIME NOT NULL COMMENT 'Captured time',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  PRIMARY KEY (comment_id),
  UNIQUE KEY uk_room_comment (room_key, dedupe_key),
  KEY idx_lead_time (lead_id, captured_at),
  KEY idx_date_nickname (lead_date, room_key, nickname),
  KEY idx_viewer_time (viewer_id, captured_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Douyin viewer comment';

CREATE TABLE IF NOT EXISTS dy_viewer_follow_record (
  record_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Follow record ID',
  lead_id BIGINT NOT NULL COMMENT 'Lead ID',
  viewer_id BIGINT DEFAULT NULL COMMENT 'Viewer ID',
  follow_content VARCHAR(1000) NOT NULL COMMENT 'Follow content',
  follow_result VARCHAR(32) DEFAULT NULL COMMENT 'interested/no_reply/ordered/rejected',
  next_follow_time DATETIME DEFAULT NULL COMMENT 'Next follow time',
  operator_id BIGINT DEFAULT NULL COMMENT 'Operator ID',
  operator_name VARCHAR(50) DEFAULT NULL COMMENT 'Operator name',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  PRIMARY KEY (record_id),
  KEY idx_lead_time (lead_id, create_time),
  KEY idx_viewer_time (viewer_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Douyin viewer follow record';

CREATE TABLE IF NOT EXISTS dy_capture_batch (
  batch_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Batch ID',
  batch_no VARCHAR(80) NOT NULL COMMENT 'Client batch number',
  room_key VARCHAR(64) NOT NULL COMMENT 'Capture room key',
  douyin_user_id VARCHAR(64) DEFAULT NULL COMMENT 'Douyin user ID',
  payload_type VARCHAR(32) NOT NULL COMMENT 'audiences/comments/heartbeat',
  source VARCHAR(64) DEFAULT NULL COMMENT 'Source',
  live_room_name VARCHAR(100) DEFAULT NULL COMMENT 'Live room name',
  page_url VARCHAR(1000) DEFAULT NULL COMMENT 'Page URL',
  request_url VARCHAR(1000) DEFAULT NULL COMMENT 'Request URL',
  queue_size INT DEFAULT 0 COMMENT 'Client queue size',
  item_count INT DEFAULT 0 COMMENT 'Payload item count',
  raw_payload JSON DEFAULT NULL COMMENT 'Raw payload',
  report_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Report time',
  PRIMARY KEY (batch_id),
  UNIQUE KEY uk_batch_no (batch_no),
  KEY idx_room_type_time (room_key, payload_type, report_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Douyin capture batch';
